# Importing Numpy Library

In [1]:
import numpy as np

# Linear Alegbra with Numpy
Linear algebra, like matrix multiplication, decompositions, determinants, and other square matrix math, is an important part of any array library. Unlike some languages like MATLAB, multiplying two two-dimensional arrays with * is an element-wise product instead of a matrix dot product. Thus, there is a function dot, both an array method and a function in the numpy namespace, for matrix multiplication:

**Creating Arrays:** NumPy provides a function called **array()** that can be used to create arrays. Arrays can be created by passing a list or a tuple of numbers to the **array()** function.

In [11]:
x = np.array([[1., 2., 3.],
              [4., 5., 6.]])

y = np.array([[6., 23.],
              [-1, 7],
              [8, 9]])

print(x)
print("\n",y)

[[1. 2. 3.]
 [4. 5. 6.]]

 [[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]


**Matrix Multiplication:** NumPy provides a function called **dot()** that can be used to perform matrix multiplication. The **dot()** function can be used to multiply two matrices or a matrix and a vector.

In [9]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [10]:
#x.dot(y) is equivalent to np.dot(x, y):
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

A matrix product between a two-dimensional array and a suitably sized one-dimensional array results in a one-dimensional array:

In [13]:
np.dot(x, np.ones(3))

array([ 6., 15.])

**numpy.linalg** has a standard set of matrix decompositions and things like inverse and determinant. These are implemented under the hood via the same industry-standard linear algebra libraries used in other languages like MATLAB and R, such as BLAS, LAPACK, or possibly (depending on your NumPy build) the proprietary Intel MKL (Math Kernel Library):

In [14]:
from numpy.linalg import inv, qr

In [19]:
X = np.random.randn(5, 5)
X

array([[ 0.61365981,  1.26088247,  0.56124188,  0.97930718, -0.57120264],
       [ 0.83473524, -0.89131741, -1.14226283,  0.64166313, -1.60306647],
       [-0.66583446, -0.44737984,  1.60185057, -0.41025029,  1.74172108],
       [-0.49842355,  0.54627824,  0.44012237,  0.98487557,  0.20004738],
       [ 0.68632202,  1.86185773,  0.90505261,  2.5843496 ,  0.10894697]])

**Transpose of a Matrix:** NumPy provides a function called **transpose(), T** that can be used to calculate the transpose of a matrix.

In [32]:
# Transpose
X.T

array([[ 0.61365981,  0.83473524, -0.66583446, -0.49842355,  0.68632202],
       [ 1.26088247, -0.89131741, -0.44737984,  0.54627824,  1.86185773],
       [ 0.56124188, -1.14226283,  1.60185057,  0.44012237,  0.90505261],
       [ 0.97930718,  0.64166313, -0.41025029,  0.98487557,  2.5843496 ],
       [-0.57120264, -1.60306647,  1.74172108,  0.20004738,  0.10894697]])

In [33]:
X.transpose()

array([[ 0.61365981,  0.83473524, -0.66583446, -0.49842355,  0.68632202],
       [ 1.26088247, -0.89131741, -0.44737984,  0.54627824,  1.86185773],
       [ 0.56124188, -1.14226283,  1.60185057,  0.44012237,  0.90505261],
       [ 0.97930718,  0.64166313, -0.41025029,  0.98487557,  2.5843496 ],
       [-0.57120264, -1.60306647,  1.74172108,  0.20004738,  0.10894697]])

**Inverse of a Matrix:** NumPy provides a function called **inv()** that can be used to calculate the inverse of a matrix.

In [25]:
mat = X.T.dot(X)

#Inverse
inv(mat)

array([[ 2.42566858, -0.02017958, -0.78285474, -0.19646482,  1.69336401],
       [-0.02017958,  0.63996055, -0.39299007, -0.31034154,  0.16463909],
       [-0.78285474, -0.39299007,  2.25468492, -0.41186112, -2.17715533],
       [-0.19646482, -0.31034154, -0.41186112,  0.54008442,  0.39181093],
       [ 1.69336401,  0.16463909, -2.17715533,  0.39181093,  2.72665213]])

In [26]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -1.25363254e-16, -1.11001831e-16,
         3.26299137e-16,  1.18664862e-16],
       [ 4.23900489e-16,  1.00000000e+00,  4.12407153e-16,
        -3.34794319e-16,  7.11129816e-16],
       [-2.74036638e-16, -2.63933302e-16,  1.00000000e+00,
        -2.35128816e-16,  1.29045468e-15],
       [ 9.03744031e-16, -1.02870778e-16, -4.73725436e-16,
         1.00000000e+00,  1.13005561e-15],
       [-8.31375421e-17, -8.55464802e-17, -2.81517864e-16,
        -1.97082311e-16,  1.00000000e+00]])

**Determinant of a Matrix:** NumPy provides a function called **det()** that can be used to calculate the determinant of a matrix.

In [34]:
a = np.array([[1, 2], [3, 4]])
b = np.linalg.det(a)
print(b)

-2.0000000000000004


In this code, mat is a square matrix, and the **qr()** function in NumPy is used to perform the QR decomposition of the matrix mat.

QR decomposition factorizes a matrix A into the product of an orthogonal matrix Q and an upper triangular matrix R. The **qr()** function in NumPy returns the factorized matrices Q and R as separate arrays.

In [29]:
q, r = qr(mat)

r

array([[-4.88938799, -4.84662313,  2.70981087, -8.54916849,  6.93687803],
       [ 0.        , -8.10334557, -7.20425446, -7.8553729 , -4.27414973],
       [ 0.        ,  0.        , -1.37191368, -0.6833949 , -1.03675289],
       [ 0.        ,  0.        ,  0.        , -1.3626009 ,  0.16047939],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.25630293]])

In [30]:
q

array([[-0.45734983,  0.10901997, -0.54732784,  0.53945317,  0.43401416],
       [-0.27266721, -0.62046459,  0.58054423,  0.44929284,  0.04219748],
       [ 0.26053416, -0.51797896, -0.55459722,  0.21181377, -0.5580113 ],
       [-0.55069263, -0.43526605, -0.21026414, -0.67304194,  0.10042229],
       [ 0.58765918, -0.38128678, -0.10775687, -0.09631045,  0.69884894]])

# Statistical Functions with Numpy
NumPy is a powerful Python library for scientific computing, which includes a wide range of mathematical functions and tools. Here are some of the most common statistical functions available in NumPy:
1. **Mean:** The **mean()** function is used to calculate the arithmetic mean of the elements in an array or a matrix.
2. **Median:** The **median()** function is used to calculate the median of the elements in an array or a matrix.
3. **Standard Deviation:** The **std()** function is used to calculate the standard deviation of the elements in an array or a matrix.
4. **Variance:** The **var()** function is used to calculate the variance of the elements in an array or a matrix.
5. **Percentiles:** The **percentile()** function is used to calculate the percentile of the elements in an array or a matrix.
6. **Correlation Coefficient:** The **corrcoef()** function is used to calculate the correlation coefficient between two arrays.
7. **Covariance:** The **np.cov()** function computes the covariance matrix of a set of data.

In [38]:
import numpy as np

# Create an array of data
data = np.array([1, 2, 3, 4, 5])

# Compute the mean of the data
mean = np.mean(data)
print("Mean:", mean)

# Compute the median of the data
median = np.median(data)
print("Median:", median)

# Compute the standard deviation of the data
std = np.std(data)
print("Standard deviation:", std)

# Compute the variance of the data
var = np.var(data)
print("Variance:", var)

# Compute the 75th percentile of the data
percentile = np.percentile(data, 75)
print("75th percentile:", percentile)

Mean: 3.0
Median: 3.0
Standard deviation: 1.4142135623730951
Variance: 2.0
75th percentile: 4.0


In [36]:
import numpy as np

# Create two arrays of data
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

# Compute the correlation coefficient between the two arrays
corr = np.corrcoef(x, y)

print(corr)

[[1. 1.]
 [1. 1.]]


In [37]:
import numpy as np

# Create an array of data
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Compute the covariance matrix of the data
cov = np.cov(data)

print(cov)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In this example, we're using the **np.random.normal()** function to generate a random sample of 1000 values from a normal distribution with mean **0** and standard deviation **1**. The loc parameter specifies the mean of the distribution, the scale parameter specifies the standard deviation, and the size parameter specifies the number of values to generate. We then print the first 10 values of the sample using slicing.

Note that Numpy has a variety of other random sampling functions, such as **np.random.uniform()** for generating samples from a uniform distribution, **np.random.exponential()** for generating samples from an exponential distribution, and many more. The syntax for these functions is similar to the example above, but with different parameters depending on the specific distribution.

In [40]:
# Generate a random sample from a normal distribution with mean 0 and standard deviation 1
sample = np.random.normal(loc=0, scale=1, size=1000)

# Print the first 10 values of the sample
print(sample[:10])

[-1.10106581  0.05992341 -0.30295911  1.28777503  0.08182908 -0.07973347
 -1.00723206  0.04583103  0.44767378 -0.56551896]


In this example, we're using the **np.random.uniform()** function to generate a random sample of 1000 values from a uniform distribution between **0** and **1**. The low parameter specifies the lower bound of the distribution, the high parameter specifies the upper bound, and the size parameter specifies the number of values to generate.

In [41]:
# Generate a random sample from a uniform distribution between 0 and 1
sample = np.random.uniform(low=0, high=1, size=1000)

# Print the first 10 values of the sample
print(sample[:10])

[0.35950166 0.13806702 0.43343764 0.96961514 0.29218492 0.10914665
 0.52434904 0.67149189 0.29792039 0.58201463]


In this example, we're using the **np.random.exponential()** function to generate a random sample of 1000 values from an exponential distribution with a mean of **2**. The scale parameter specifies the scale parameter of the distribution, which is equal to the inverse of the mean. The size parameter specifies the number of values to generate.

In [42]:
# Generate a random sample from an exponential distribution with mean 2
sample = np.random.exponential(scale=2, size=1000)

# Print the first 10 values of the sample
print(sample[:10])

[2.21177986 2.1943015  0.05332413 0.12722464 1.15619478 3.2555581
 1.44576637 2.22047575 1.82392606 1.52251735]


Note that Numpy has many other random sampling functions for different distributions, such as **np.random.normal()** for generating samples from a normal distribution, **np.random.poisson()** for generating samples from a Poisson distribution, **np.random.gamma()** for generating samples from a gamma distribution, and many more. The syntax for these functions is similar to the examples above, but with different parameters depending on the specific distribution.