# Introduction to NumPy
Short for Numerical Python, has long been a cornerstone of numerical com‐
puting in Python. It provides the data structures, algorithms, and library glue needed
for most scientific applications involving numerical data in Python. NumPy contains,
among other things:

• A fast and efficient multidimensional array object ndarray.

• Functions for performing element-wise computations with arrays or mathemati‐cal operations between arrays.

• Tools for reading and writing array-based datasets to disk.

• Linear algebra operations, Fourier transform, and random number generation.

• A mature C API to enable Python extensions and native C or C++ code to access NumPy’s data structures and computational facilities.

To work with NumPy, you first need to import the library:

In [1]:
import numpy as np

Creating a NumPy array can be done in several ways, but the most common way is by passing a Python list to the **np.array()** function. For example:

# NumPy Array
A NumPy array is a **multi-dimensional** container of elements of the same data type. The array object in NumPy is called ndarray. The ndarray object is similar to a list or a tuple, but it is more efficient and powerful for numerical computations.

In [2]:
array = np.array(["Hafiz","Hassan", "Mustafa", 2, 3])
print(array)

['Hafiz' 'Hassan' 'Mustafa' '2' '3']


In [3]:
print(type(array))

<class 'numpy.ndarray'>


This creates a **one-dimensional array** of integers and strings. You can also create **multi-dimensional arrays** by passing nested lists.

NumPy arrays have some important attributes that you should be aware of:

**ndarray.ndim**: returns the number of dimensions of the array.

**ndarray.shape**: returns a tuple indicating the size of each dimension of the array.

**ndarray.size**: returns the total number of elements in the array.

**ndarray.dtype**: returns the data type of the elements in the array.

In [4]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
type(array)

numpy.ndarray

In [6]:
print(array.ndim)

2


In [7]:
print(array.shape)

(3, 3)


In [8]:
print(array.size)

9


In [9]:
print(array.dtype)

int32


NumPy arrays can be indexed and sliced like Python lists and tuples. You can access individual elements, subsets of elements, and entire rows and columns of the array.

In [10]:
print(array[0])

[1 2 3]


In [11]:
print(array[1:3])

[[4 5 6]
 [7 8 9]]


# NumPy Functions
1) **np.zeros()** that creates an array of a given shape and type, filled with zeros.

2) **np.ones()** that creates an array of a given shape and type, filled with ones.

3) **np.random.rand()** that creates an array of random values with a given shape.

4) **np.arange()** that creates an array with evenly spaced values within a given interval.

Once you have created a NumPy array, you can access its elements using indexing and slicing, just like you would with a regular Python list:

In [12]:
array = np.zeros((3,3), dtype=int, order='C')
array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [13]:
array = np.ones((3,6), dtype=int, order='C')
array

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [14]:
array = np.random.rand(3,5)
array

array([[0.45407788, 0.20161646, 0.02328179, 0.22849844, 0.67048805],
       [0.43070983, 0.79875095, 0.90713286, 0.31533983, 0.49968154],
       [0.13198884, 0.5793321 , 0.30132602, 0.34843259, 0.56642343]])

In [15]:
#np.arange(start, stop, step, dtype=None)

array = np.arange(1, 25, 2, dtype = int)
array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

NumPy also provides various mathematical operations for arrays, such as **addition**, **subtraction**, **multiplication**, **division**, **dot product**, and more. These operations can be performed element-wise or with entire arrays, depending on the specific operation and arguments used.

In [16]:
addition_arr = array + 10
addition_arr

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

In [17]:
subtraction_arr = array - 10
subtraction_arr

array([-9, -7, -5, -3, -1,  1,  3,  5,  7,  9, 11, 13])

In [18]:
multiplication_arr = array * 100
multiplication_arr

array([ 100,  300,  500,  700,  900, 1100, 1300, 1500, 1700, 1900, 2100,
       2300])

In [19]:
division_arr = array / 10
division_arr

array([0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.1, 2.3])

In [20]:
# create two arrays of the same shape
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# addition
c = a + b
print("Addition:\n", c)

Addition:
 [[ 6  8]
 [10 12]]


In [21]:
# subtraction
d = a - b
print("Subtraction:\n", d)

Subtraction:
 [[-4 -4]
 [-4 -4]]


In [22]:
# multiplication (element-wise)
e = a * b
print("Element-wise multiplication:\n", e)

Element-wise multiplication:
 [[ 5 12]
 [21 32]]


In [23]:
# division (element-wise)
f = a / b
print("Element-wise division:\n", f)

Element-wise division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [24]:
# dot product
g = np.dot(a, b)
print("Dot product:\n", g)

Dot product:
 [[19 22]
 [43 50]]


In [25]:
# sum of all elements
h = np.sum(a)
print("Sum of all elements in a:\n", h)

Sum of all elements in a:
 10
