# Importing the Numpy library

In [1]:
import numpy as np

# Broadcasting in Numpy Array
Operations between differently sized arrays is called **broadcasting.**

In Numpy, broadcasting is a powerful mechanism that allows arrays with different shapes to be used in arithmetic operations. When operating on arrays with different shapes, Numpy automatically broadcasts the smaller array across the larger array so that they have compatible shapes.

Here's an example to demonstrate broadcasting:

In [10]:
import numpy as np

a = np.array([1, 2, 3])
b = 2
c = np.array([4, 5, 6])

# Elementwise multiplication using broadcasting
result = a * b * c
print(np.shape(a)) #It returns Tuple.
print(result)

(3,)
[ 8 20 36]


In the example above, b is a scalar value and has a shape of (). However, Numpy automatically broadcasts it to a shape of (3,) so that it can be multiplied element-wise with a and c, which have shapes of (3,) and (3,) respectively.

Numpy broadcasting rules are as follows:

1. If the arrays have different numbers of dimensions, the smaller array is padded with ones on its left side.
2. If the shape of the two arrays in a dimension is the same, or one of them has a size of 1, then they are compatible.
3. If the arrays have different shapes and are not compatible, a ValueError is raised.

It's important to note that broadcasting can be computationally expensive, so it's best to use it judiciously and understand how it works under the hood.

In [5]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])   

# Elementwise addition using broadcasting
result = a + b
print(result)

[[11 22 33]
 [14 25 36]]


In [16]:
np.shape(a)

(2, 3)

In [7]:
a = np.array([[1.5, 2],
              [3.5, 4]])

b = np.array([10, 20])

# Elementwise multiplication using broadcasting
result = a * b
print(result)

[[15. 40.]
 [35. 80.]]


In this example, a is a 3x3 array of ones, and b is a 1D array with values 1, 2, and 3. The expression **b[:, np.newaxis]** reshapes b into a column vector with shape (3, 1). Then, broadcasting is used to multiply the two arrays element-wise, resulting in a new 3x3 array c where each row is multiplied by the corresponding element of b.

In [1]:
# Create a 3x3 array of ones
a = np.ones((3, 3))

# Create a 1D array with values 1, 2, and 3
b = np.array([1, 2, 3])

# Multiply the arrays using broadcasting
c = a * b[:, np.newaxis]

# Print the result
print(c)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]
