# Enumerate Function
The **enumerate()** function in Python is a built-in function that returns an iterator object that generates a sequence of tuples, each containing an index and the corresponding item from an iterable object (such as a list, tuple, string, or dictionary).

In [7]:
!python -V

Python 3.8.16


In [1]:
fruits = ["Apple","Banana","Orange","Mango","Pineapple","Grapefruit","Kiwi","Watermelon","Cantaloupe","Honeydew","Strawberry",
          "Blueberry","Raspberry","Blackberry","Cherry","Peach","Pear","Plum","Apricot","Papaya","Guava","Coconut","Pomegranate",
          "Fig","Passionfruit","Grape","Lemon","Lime","Avocado","Tomato"]

print(list(enumerate(fruits)))

[(0, 'Apple'), (1, 'Banana'), (2, 'Orange'), (3, 'Mango'), (4, 'Pineapple'), (5, 'Grapefruit'), (6, 'Kiwi'), (7, 'Watermelon'), (8, 'Cantaloupe'), (9, 'Honeydew'), (10, 'Strawberry'), (11, 'Blueberry'), (12, 'Raspberry'), (13, 'Blackberry'), (14, 'Cherry'), (15, 'Peach'), (16, 'Pear'), (17, 'Plum'), (18, 'Apricot'), (19, 'Papaya'), (20, 'Guava'), (21, 'Coconut'), (22, 'Pomegranate'), (23, 'Fig'), (24, 'Passionfruit'), (25, 'Grape'), (26, 'Lemon'), (27, 'Lime'), (28, 'Avocado'), (29, 'Tomato')]


In [2]:
for ele in enumerate(fruits):
    print (ele)

(0, 'Apple')
(1, 'Banana')
(2, 'Orange')
(3, 'Mango')
(4, 'Pineapple')
(5, 'Grapefruit')
(6, 'Kiwi')
(7, 'Watermelon')
(8, 'Cantaloupe')
(9, 'Honeydew')
(10, 'Strawberry')
(11, 'Blueberry')
(12, 'Raspberry')
(13, 'Blackberry')
(14, 'Cherry')
(15, 'Peach')
(16, 'Pear')
(17, 'Plum')
(18, 'Apricot')
(19, 'Papaya')
(20, 'Guava')
(21, 'Coconut')
(22, 'Pomegranate')
(23, 'Fig')
(24, 'Passionfruit')
(25, 'Grape')
(26, 'Lemon')
(27, 'Lime')
(28, 'Avocado')
(29, 'Tomato')


In [3]:
# changing index and printing separately
for count, ele in enumerate(fruits, 50):
    print (count, ele)

50 Apple
51 Banana
52 Orange
53 Mango
54 Pineapple
55 Grapefruit
56 Kiwi
57 Watermelon
58 Cantaloupe
59 Honeydew
60 Strawberry
61 Blueberry
62 Raspberry
63 Blackberry
64 Cherry
65 Peach
66 Pear
67 Plum
68 Apricot
69 Papaya
70 Guava
71 Coconut
72 Pomegranate
73 Fig
74 Passionfruit
75 Grape
76 Lemon
77 Lime
78 Avocado
79 Tomato


# Timing your code
Python executes 10⁷ operations per second.

To time your code you will need a time library. In this library, there is a perf_counter() function which is a performance counter.

perf_counter(): It returns the float value of time in seconds. It gives you the absolute value.

perf_counter_ns(): It returns the float value of time in nanoseconds.

In [4]:
import numpy as np
import time

start_time = time.perf_counter()

data = np.arange(1,11)
multi = data * data
sub = data - 1
add = data + 1
div= data / 2
print(data)
print("----------------------------------------------")
print(multi)
print("----------------------------------------------")
print(sub)
print("----------------------------------------------")
print(add)
print("----------------------------------------------")
print(div)

end_time = time.perf_counter()

elapsed_time = end_time - start_time
print(f"Elapsed time: {elapsed_time:.6f} seconds")

[ 1  2  3  4  5  6  7  8  9 10]
----------------------------------------------
[  1   4   9  16  25  36  49  64  81 100]
----------------------------------------------
[0 1 2 3 4 5 6 7 8 9]
----------------------------------------------
[ 2  3  4  5  6  7  8  9 10 11]
----------------------------------------------
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
Elapsed time: 0.001563 seconds


In [5]:
t0 = time.time()

data = np.arange(1,11)
multi = data * data
sub = data - 1
add = data + 1
div= data / 2
print(data)
print("----------------------------------------------")
print(multi)
print("----------------------------------------------")
print(sub)
print("----------------------------------------------")
print(add)
print("----------------------------------------------")
print(div)

t1 = time.time()

total = t1-t0
total

[ 1  2  3  4  5  6  7  8  9 10]
----------------------------------------------
[  1   4   9  16  25  36  49  64  81 100]
----------------------------------------------
[0 1 2 3 4 5 6 7 8 9]
----------------------------------------------
[ 2  3  4  5  6  7  8  9 10 11]
----------------------------------------------
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


0.00299835205078125

In [6]:
# Difference of perf_counter() function & time() function
final = total - elapsed_time
final

0.0014352520507814326

In [8]:
from datetime import datetime

date_and_time = datetime.now()
print("The today current date and time is:-" , date_and_time)

The today current date and time is:- 2023-03-21 12:20:22.210892


# User Inputs
User input refers to the data or information that a program receives from the user during runtime. In Python, you can prompt the user to input data using the built-in **input()** function. When the **input()** function is executed, the program pauses and waits for the user to enter data. Once the user inputs data and presses the "Enter" key, the program resumes and the input data is returned as a string.

In [9]:
Radius = float(input("Enter the radius of circle: "))
Area = 3.14159 * (Radius*Radius)
print("Area of circle is: ", Area, "square units")

Enter the radius of circle: 5
Area of circle is:  78.53975 square units


In [12]:
a = float(input("Enter first number: "));
b = float(input("Enter second number: "));
c = a + b;
print("Total:",float(c))

Enter first number: 5
Enter second number: 9
Total: 14.0


In [13]:
#This code can be used to print any input string in reverse order, not just names.
name = input("Enter your full name: ")

for char in range(len(name) - 1, -1, -1):
  print(name[char], end="")
print("\n")

Enter your full name: Hafiz Hassan Mustafa
afatsuM nassaH zifaH



# Conditionals
Conditionals, also known as conditional statements, are programming constructs that allow you to execute different blocks of code based on whether a certain condition is true or false. In Python, there are two types of conditional statements: if statements and if-else statements.

In [20]:
# Ticketing charges
name = str(input("Enter your name: "))
age = int(input("Enter your age: "))

if age < 10:
    print("----------------------------------")
    print("You are eligible for child ticket.")
elif age > 10 & age < 30:
    print("-------------------------------------------------------")
    print("You are eligible for student ticket & get 10% discount.")
else:
    print("--------------------------------------")
    print("You are not eligible for adult ticket.")

Enter your name: Hafiz Hassan Mustafa
Enter your age: 23
-------------------------------------------------------
You are eligible for student ticket & get 10% discount.


# Introducing Set
In Python, a set is an unordered collection of unique elements. This means that a set can contain only one instance of each element, and the order in which the elements appear in the set is not important. Sets are similar to lists and tuples, but unlike lists and tuples, they do not support indexing or slicing.
Various set operations are performed using the **|, &, -, and ^** operators.

In [23]:
set1 = {"Hassan", "Ahsan", "Hasnain"}
set2 = {"Hassan","Saad","Faraz"}

print(set1 | set2) #Union
print(set1 & set2) #Intersection
print(set1 - set2) #Difference
print(set1 ^ set2) #Symmetric difference

{'Ahsan', 'Faraz', 'Hassan', 'Saad', 'Hasnain'}
{'Hassan'}
{'Ahsan', 'Hasnain'}
{'Ahsan', 'Faraz', 'Saad', 'Hasnain'}


# 2nd Approach
In this code, two sets (data1 and data2) are defined, and various set operations are performed using the **.union(), .intersection(), .difference(), and .symmetric_difference()** methods.

In [34]:
data1 = set([1,2,3,4,5])
data2 = set([5,6,7,8,9])
print(type(data1),type(data2))

<class 'set'> <class 'set'>


# Union

In [35]:
final_data = data1.union(data2)
print(type(final_data))
print("Final Uninion:", final_data)

<class 'set'>
Final Uninion: {1, 2, 3, 4, 5, 6, 7, 8, 9}


# Intersection

In [36]:
final_data = data1.intersection(data2)
print(type(final_data))
print("Final Intersection:", final_data)

<class 'set'>
Final Intersection: {5}


# Difference

In [37]:
final_data = data1.difference(data2)
print(type(final_data))
print("Final Difference:", final_data)

<class 'set'>
Final Difference: {1, 2, 3, 4}


# Symmetric Difference

In [38]:
final_data = data1.symmetric_difference(data2)
print(type(final_data))
print("Final Symmetric Difference: ", final_data)

<class 'set'>
Final Symmetric Difference:  {1, 2, 3, 4, 6, 7, 8, 9}
